% config parameters
% Direction is defined in "AdapterboardDirections.jpg"

% rotating the sensor about yaw (inertia) axis with roll = 0°, pitch = 0°

columns = {'acX', 'acY', 'acZ', ...
           'gyX', 'gyY', 'gyZ', ...
           'magX', 'magY', 'magZ', ...
           'pressure', 'timestampStartReadingSensors', 'timestampFinishedReadingSensors'};
