% config parameters
% Direction is defined in "AdapterboardDirections.jpg"

% rotating the sensor about the roll axis

columns = {'acX', 'acY', 'acZ', ...
           'gyX', 'gyY', 'gyZ', ...
           'magX', 'magY', 'magZ', ...
           'pressure', 'timestampStartReadingSensors', 'timestampFinishedReadingSensors'};
